name: Publish Package to npmjs
on:
    push:
        branches:
            - main
        tags:
            - 'v*'
        paths:
            - 'src/**'
            - './*.json'
            - './*.js'
            - '.github/workflows/publish-on-npmjs.yml'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            PRE_RELEASE: contains(fromJson(env.PACKAGE_JSON).version, 'alpha')
        steps:
            - uses: actions/checkout@v2
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: |
                npm ci
                npm run build
                npm run dist 
            - run: |
                cd package
                echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
                cat ./package.json >> $GITHUB_ENV
                echo 'EOF' >> $GITHUB_ENV  
            - name: Stable version
              if: ${{ !env.PRE_RELEASE }}
              run: cd package && npm publish --access=public
              env:
                 NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Pre-release version
              if: ${{ env.PRE_RELEASE }}
              run: cd package && npm publish --tag next --access=public
              env:
                 NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
